package com.rabbitv.valheimviki.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val DETAIL_ITEM_SHAPE_PADDING = 8.dp

//GRID
val ITEM_HEIGHT_ONE_COLUMNS = 250.dp
val ITEM_HEIGHT_TWO_COLUMNS = 200.dp
val ITEM_HEIGHT_THREE_COLUMNS = 150.dp

//LIST
val DEFAULT_LIST_ITEM_HEIGHT = 80.dp
val DEFAULT_WITH_LIST_IMAGE = 120.dp

val ICON_CLICK_DIM = 48.dp
val ICON_SIZE_THIRD = 32.dp
val ICON_SIZE_SECOND = 28.dp
val ICON_SIZE = 24.dp

val CUSTOM_ITEM_CARD_FILL_WIDTH = 0.47f


const val DEFAULT_MINIMUM_TEXT_LINE = 4
const val BODY_CONTENT_PADDING = 10